- name: Create servers with group and no increment
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Server build requests
      local_action:
        module: rax
        credentials: ~/.raxpub
        name: test
        flavor: performance1-1
        image: ubuntu-1204-lts-precise-pangolin
        disk_config: manual
        networks:
            - public
            - private
        region: IAD
        state: present
        count: 2
        auto_increment: no
        group: test
        wait: yes
      register: rax